### ISSUE TITLE
move the pdf attachments  and link them

### ISSUE THREAD

**Issue by jlu511** [wileyyugioh/zotmoov#2]
would you add a feature that can move the pdf attachments to the "folder" and link them. 
the feature  will allow exporting attachments of items in the Zotero Library or selected collection as files organized in "folders". The exported attachments (files) will be organized in "folders" which reflect the hierarchical structure of the selected Zotero Library/Collections. 
For example, a reference is in "My Library/A/B", and "move the pdf attachments  and link them" will move the PDF to "zotero home directory/A/B" folder, and link it.

this maybe is helpful.  https://github.com/retorquere/zotero-file-hierarchy

thank you

**Comment by wileyyugioh** [comment]
If I'm understanding right, you want the folder that the files are being moved to organized by collection. I can see some challenges/problems with this feature.

1. What happens if the file is in multiple collections? Duplicating the file to put into each folder seems inefficient.
2. What happens if the file is later moved/removed from a collection? Would we have to reorganize the folder?

I think the best approach for now is using Zotero to manage these hierarchies and exporting the PDFs directly through native Zotero or another extension such as the one you linked.

**Comment by wileyyugioh** [comment]
The feature added in https://github.com/wileyyugioh/zotmoov/issues/5 allows users to manually move and link files into the directory of their choice. This is useful for files that reside only in one collection, but may lead to confusion for files in multiple collections since each file only resides in a single folder and is not duplicated
