### ISSUE TITLE
Request: Subdirectory setting for moving files manually

### ISSUE THREAD

**Issue by lyrebird23** [wileyyugioh/zotmoov#25]
Hello, 

Thank you for building this extension. It is proving to be very helpful. 

When I decide to read a paper, I want to be able to move it into a subdirectory called "Reading". At the moment, when I right-click on the PDF file and select "Move to selected custom directory", a pop-up window appears so that I can choose a directory. But this will get tedious if I have lots of files to move. I would like to be able to set the directory name in the settings, and just select a menu item to move to that directory. 

I have tried putting the directory name into the "Automatically move/copy files to subdirectory" setting, but I have that setting turned off because I don't want the files to be moved there automatically. And it doesn't seem to pick up the directory name I have entered when the setting is turned off. 

Is this making any sense?
Also, thank you for writing this extension. :D

**Comment by wileyyugioh** [comment]
You can also try disabling the Automatically Move/Copy Files When Added and enabling the Automatically Move/Copy Files to Subdirectory. This will make it so that only when you right click and use the Move Selected to Directory will files be moved to the Reading folder.

![Screen Shot 2024-04-03 at 19 13 06](https://github.com/wileyyugioh/zotmoov/assets/9703998/7632b629-6969-46b3-ab13-e70ebd37cc63)
