### ISSUE TITLE
Replicate Send to Tablet and Get from tablet from Zotfile

### ISSUE THREAD

**Issue by JanPastorek** [wileyyugioh/zotmoov#44]
Hi,

I think there is a big group of people waiting for functions "Send to Tablet" and  "Get from tablet" from Zotfile to be implemented in either Attanger or Zotmoov, see [https://forums.zotero.org/discussion/116679/zotero-7-and-zotfile](https://forums.zotero.org/discussion/116679/zotero-7-and-zotfile)

I believe Zotmoov has all the necessary functionalities already available. In Zotfile it worked like this:
1. By right clicking on a certain item in library, you had available option to "Send to Tablet"
2. If clicked, this assigned a tag to the item →  _tablet   and copied the file to specified directory in the settings
3. Then we markup on tablet, selecting and annotating a PDF in that specified directory
4. By right clicking on that item in library again, we have available option to "Get from Tablet" which pulls selections and annotations in PDF and extracts them as notes, and takes away the _tablet tag, and it moves the annotated copy of the original file to the storage (which now has +1 pdf files, one of them is the annotated one).

Thank you for consideration!
All the best

**Comment by jryans** [comment]
The file moving portions of ZotFile already exist here in ZotMoov some form or another. Perhaps you're already aware of this, but just for clarity, I'll try to convert your ZotFile steps into equivalent ZotMoov steps.

As prep work, [get your ZotFile tablet files back](https://github.com/wileyyugioh/zotmoov#migrating-from-zotfile) from tablet, as ZotMoov stores them differently. Set your linked attachment base directory to the tablet directory.

1. To send a file, right-click and choose "ZotMoov: Move Selected to Directory"
2. The file is moved to the tablet (or copied depending on preferences)
  * ZotMoov does not currently set a tag on moved / copied items
3. Markup the PDF as before
4. To get a file back, right-click and choose "ZotMoov: Move Selected from Directory"
  * ZotMoov does not process annotations, but you can read / import them in Zotero's PDF reader
  * In move mode, ZotMoov just moves PDFs, so there won't be an extra PDF, but rather only the annotated one. (Maybe copy mode does leave an extra file, haven't used that myself.)

So, the core moving / copying functions are already there. Which of the remaining pieces are essential to your workflow (if any)...? That may help @wileyyugioh decide whether they are a good fit for ZotMoov.

**Comment by JanPastorek** [comment]
I will add this discussion to Zotero forums so that more people will have their say. 

For myself, it would be great to replicate all of 1. - 4. that you described under two buttons - send to to tablet (1.-2.), get from tablet (4.) . Setting a tag is especially important to have a clear view that these files are currently annotated on tablet. Getting the annotated extra PDF file is important as well.

**Comment by StoyanPv** [comment]
I endorse this request!

**Comment by boolanger** [comment]
Same!

One thing to have in mind is that one may want to have the tablet directory separate from the linked attachment base directory (this is possible in ZotFile).

**Comment by zouyonghao** [comment]
I also need this. My files are synced using WebDAV but I don't want to sync all files to my e-reader.

**Comment by EbiAG** [comment]
This is something I also relied on with Zotfile. It would be great to have it with ZotMoov!

**Comment by zouyonghao** [comment]
I made a very simple plugin [here](https://github.com/zouyonghao/zotero-sync-to-tablet) to support my needs. It only has features including setting the destination folder (in the Settings), send a file to the folder and retrieve a file from the folder.

**Comment by tom-mclean** [comment]
Is there a (non-technically complex) way of installing ZotMoov twice? (Also: that doesn't break everything...)

So far, I've set ZotMoov up to do one of the two remaining tasks I used Zotfile for: moving files I add to Zotero to the folder I want them stored in. (I want to be able to store files in folders by author, whereas natively Zotero only seems to tolerate putting them in a single folder. With 3000+ items in my library and wanting to be able to access them directly and not just through Zotero, folders are essential!).

The other task is that of moving files to my tablet when I want to read them remotely. As mentioned in the thread, being able to tag them when doing so would be ideal, but I can manage without that. With a second instance of ZotMoov, it could also be used to send to and retrieve from my tablet. 

This presumably needs a safeguard built in so that it can't descend into an infinite loop of automatic moves, but otherwise presumably doesn't need to change much? (An instance without the automatic options perhaps?)

**Comment by wileyyugioh** [comment]
@tom-mclean A feature that will be in the upcoming 1.2 beta release is custom menu items. So you can create your own custom menu item that will move it to the directory you specify and add tags. All of the main features for 1.2 are already coded---I want some time to check for bugs. So the 1.2 beta should be released in the next few weeks. Sit tight!

**Comment by wileyyugioh** [comment]
The [latest beta version](https://github.com/wileyyugioh/zotmoov/releases/tag/1.2.0) has the ability to define a custom menu item. This includes moving files to a specific directory, extracting annotations, and moving files back into Zotero.

**Comment by JanPastorek** [comment]
thank you, finally I think I am ready to move to Zotero 7 :)

**Comment by JanPastorek** [comment]
@wileyyugioh I tried it, and everything except "Copy To" function seems to work. "Copy to" makes a new file, however, it is not linked to the Item in the zotero.

**Comment by wileyyugioh** [comment]
@JanPastorek that’s correct. Copy to is for making backup of files without linking them to Zotero.

**Comment by blogfar** [comment]
Thank you so much for these amazing changes! Is there actually a way to make the "Add Tag" option to actually add the tag to the parent metadata, so that the tag would be visible next to other tags?

![image](https://github.com/user-attachments/assets/14d50845-9466-44a7-9bdd-f27ff1e10c76)

This is what I get now from adding "Add Tag" to my "Send to Tablet" custom menu item. It is however just a small pushback, I can always use hotkeys and attach the tag manually.

**Comment by tom-mclean** [comment]
I'm still having issues with setting up a "Get from Tablet" command. ("Send to Tablet" appears to be working fine).

I have the commands as in the attached screenshot: Move From; Annotation to Note; Remove Tag.
<img width="687" alt="Screenshot 2024-11-25 at 12 54 45" src="https://github.com/user-attachments/assets/d5928e67-f9a7-433c-9a1b-e77d1a537693">

When I use the "Get" command, the file appears in the storage folders (with random alphanumeric names) which are the default storage location for Zotero, not the folders its come from, without any of the annotations I've added on my tablet. The file is also not removed from the tablet storage location (though that version retains the annotations). The tag is not removed in Zotero.

I've also tried setting up the command using the "Move To" option (setting the custom directory to the root folder of my library, and enabling the subdirectory option to get into the right folder). In this case, the file doesn't seem to appear in the randomly assigned folders, but annotations are not present in the version in Zotero, and again it is removed from the tablet location.

Am I doing something wrong?

**Comment by wileyyugioh** [comment]
@blogfar Yes, I will add an option in the next update that will also let you add a tag to the parent item. Also I think I found the bug that causes the add tag to sometimes not work.

**Comment by wileyyugioh** [comment]
@tom-mclean The second option would be the way to go. I'm surprised the annotations are not present. Do you mean the note isn't created, or the annotation in the PDF disappears?

**Comment by tom-mclean** [comment]
That still seems to be behaving slightly oddly.

I had had the "Send to Tablet" command set up with "Copy To" rather than "Move To" and on "Copy To" it seems much less convinced about subsequently moving anything back. So I've changed to "Move To", which moves the file to the Tablet location happily. BUT... when I "Get From Tablet" the annotations are imported and the tag removed, but the file gets left in the Tablet location (and Zotero identifies as there, and not in the usual folder).

Commands set up as illustrated.

<img width="597" alt="Screenshot 2024-11-26 at 12 06 55" src="https://github.com/user-attachments/assets/e1124e92-477e-49b7-97ca-dbf5e94bdd45">

<img width="617" alt="Screenshot 2024-11-26 at 12 07 48" src="https://github.com/user-attachments/assets/24e0bec6-6ccd-4d39-a756-fc41587734af">

**Comment by wileyyugioh** [comment]
> I had had the "Send to Tablet" command set up with "Copy To" rather than "Move To" and on "Copy To" it seems much less convinced about subsequently moving anything back. So I've changed to "Move To", which moves the file to the Tablet location happily. BUT... when I "Get From Tablet" the annotations are imported and the tag removed, but the file gets left in the Tablet location (and Zotero identifies as there, and not in the usual folder).

Copy To is simply for making backups of your PDF. Once the copy is made, it is not tracked at all and cannot be reimported. You definitely want to use Move To. The file that was left in the Tablet folder is probably just the copied file.

**Comment by wileyyugioh** [comment]
@blogfar @tom-mclean 1.2.6 added the ability to change the tags of parent items and has some bug fixes that should make the custom menu items more reliable.

**Comment by tom-mclean** [comment]
Thank you!

With 1.2.6, my problem seems (in a quick test so far) to have been resolved. Files are moving back and forth as I would likely.

I think what you've built is working slightly differently to how I had ZotFile working before in that I don't think ZotFile moved the file from the main collection location to the tablet location, rather it copied it and then replaced the original when it moved a copy back. However, as Zotero links to the moved file, there's only a very limited set of circumstances in which that's going to cause me any problems!

**Comment by andyjrogers** [comment]
Thank you all for the work and tips here, I've copied the commands above and it's working great. 

Just wanted to ask if there is a way to duplicate the attachment so that ultimately after sending back and forth there's a "clean" version of the PDF and an annotated one? I'm annotating papers on my Remarkable so the annotations aren't readable by Zotero or removable by a PDF reader, so it would be useful to maintain the original version for sending to colleagues etc. It could be that I use the Copy To option, and backup the clean versions to a separate folder outside of Zotero that I can delve into if I ever need a clean version, which may be simpler. But just wanted to see if anybody had any thoughts first!

**Comment by wileyyugioh** [comment]
I am going to close this comment thread. Please create a new one for any bugs/new feature requests.

**Comment by rohanmtandon** [comment]
@JanPastorek Hi, thanks for requesting this feature update. When you move a file to the selected directory (eg on Google Drive) to then access from your iPad/tablet, what does your workflow look like to annotate? I am currently confused how I can annotate on my iPad and then 'send back to my computer' - would appreciate the support!
