### ISSUE TITLE
Attachment name not changed upon changing parent metadata

### ISSUE THREAD

**Issue by martijnende** [wileyyugioh/zotmoov#56]
### Problem description

I've come across certain behaviour of which I'm not sure it is a bug or a feature. To reproduce this behaviour, consider the following scenario:

1. I have a publication by Alice & Bob (2020) located in the subcollection "Foo". The associated PDF is named according to the Zotero naming conventions (`{{ firstCreator suffix=" " }}{{ year suffix=" -- " }}{{ title truncate="100" }}`).
2. I change the author metadata to Alice & Charlie (2020).
3. When I right-click `ZotMoov: Move Selected to Directory`, nothing happens. This is not entirely unexpected, because the file is already in the right directory, but I had hoped it would rename the file to "Alice & Charlie [...].pdf".
4. When I move the parent item to the subcollection "Bar" and click `ZotMoov: Move Selected to Directory`, the PDF is moved but not renamed.
5. When I right-click the PDF and `Rename File from Parent Metadata`, the file is renamed, but the linked item as seen in the Zotero library keeps its original name (unless I change it manually).

This behaviour seems a bit unproductive, and I would like that upon updating the parent metadata, I can simply hit `ZotMoov: Move Selected to Directory` to update the file name (not just the directory) and the item name in Zotero. Is there something I am missing here?

### Additional info

Zotero version `7.0.7`
ZotMoov version `1.1.14`
Under Zotero settings > General > File Renaming I checked "Rename linked files"

**Comment by wileyyugioh** [comment]
Zotmoov only runs the move operation (which includes title renaming) if the destination file path and the current file path are different. The file renaming is done entirely by Zotero. What I suspect is happening in your case is:

1. The attachment is already linked and moved and is a child item of the Zotero entry
2. You click the Zotero rename from parent metadata. This updates the attachment file name **but not the title** because the Zotero devs want to decouple the title and file name.
3. You click the Move Selected menu item. Zotmoov checks that the destination file path and the current file path are the same, skipping the move operation. So the title is not properly updated to match the file name.

Something you can do currently is make sure the renaming is done before converting the stored file to a linked file.

It does make sense to me that we should update the title in your scenario since most users want it to match, so I’ll likely add it in a future update.

**Comment by martijnende** [comment]
Thanks @wileyyugioh for getting back to me so quickly.

> Zotmoov only runs the move operation (which includes title renaming) if the destination file path and the current file path are different.

I tested this by changing the parent item's metadata, moving the parent item to a different subcollection, and then clicking `ZotMoov: Move Selected to Directory`. Each subcollection resides in a different directory. I can see that the attachment is relocated to the new directory, but the file name is not changed according to the parent's updated metadata. So it seems that ZotMoov does not rename the attachment when performing the move.

@TW96 indeed, I was thinking of Zotfile's "Rename & Move" functionality.

**Comment by wileyyugioh** [comment]
The [latest beta version](https://github.com/wileyyugioh/zotmoov/releases/tag/1.2.0) should always rename the file. Please let me know if this is fixed.
